[package]
name = "file-async-rpc"
version = "0.1.0"
edition = "2021"
authors = ["Asklv <boironic@gmail.com>"]

[dependencies]
async-trait = "0.1.80"
flume = "0.11.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"